# Pass in project directory containing fastq_pass directory (inFile) and reference genome (fnaFile)
bam_file=$1
workflow_dir=$2
flowcell_dir=$3
baseflowcell=$4
svSet=$5

# Necessary for Nextflow to speak with the LSF scheduling platform
export NXF_CLUSTER_SEED=$(shuf -i 0-16777216 -n 1)

# Call pipeline
~/.conda/envs/nextflow_env/bin/nextflow run --bamfile ${bam_file} --dirstring ${workflow_dir} --runstring ${baseflowcell} --svSet ${svSet} run_Sniffles2.nf -c nextflow.config  

# Fix permissions for files generated by nextflow pipeline
chmod -R 770 ${workflow_dir}
